# Generated by Django 5.0.4 on 2024-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
